import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import type Database from 'better-sqlite3'
import { persistGeneratedCharacterPortrait } from '../db/repositories/characters'
import { mimeTypeToExtension } from './npcFaceTokenAsset'

/** Player icons share the uploaded-portrait app-data folder (epic 009 / 144). */
export const PLAYER_CHARACTER_ICON_SUBFOLDER = 'portraits'

function buildPlayerCharacterIconFilePath(
  baseDir: string,
  characterId: string,
  mimeType: string
): string | null {
  const extension = mimeTypeToExtension(mimeType)
  if (!extension) {
    return null
  }
  return join(baseDir, PLAYER_CHARACTER_ICON_SUBFOLDER, `${characterId}${extension}`)
}

interface WritePlayerCharacterIconAssetInput {
  baseDir: string
  characterId: string
  bytesBase64: string
  mimeType: string
}

export function writePlayerCharacterIconAsset(
  input: WritePlayerCharacterIconAssetInput
): string | null {
  const filePath = buildPlayerCharacterIconFilePath(
    input.baseDir,
    input.characterId,
    input.mimeType
  )
  if (!filePath) {
    return null
  }
  mkdirSync(dirname(filePath), { recursive: true })
  writeFileSync(filePath, Buffer.from(input.bytesBase64, 'base64'))
  return filePath
}

interface PersistPlayerCharacterIconAssetInput {
  characterId: string
  bytesBase64: string
  mimeType: string
  appearancePrompt: string
  baseDir: string
}

/**
 * Write generated bytes and bind portrait_path + portrait_prompt.
 * Only call on successful generation — failure must leave prior path intact.
 */
export function persistPlayerCharacterIconAsset(
  db: Database.Database,
  input: PersistPlayerCharacterIconAssetInput
): string | null {
  const filePath = writePlayerCharacterIconAsset({
    baseDir: input.baseDir,
    characterId: input.characterId,
    bytesBase64: input.bytesBase64,
    mimeType: input.mimeType
  })
  if (!filePath) {
    return null
  }
  persistGeneratedCharacterPortrait(db, input.characterId, filePath, input.appearancePrompt)
  return filePath
}
