import type { Temperament } from '../../../shared/alignment/types'
import type { CreateCatalogCreatureInput } from '../types'

const CREATURE_BEHAVIOR: Record<string, { temperament: Temperament; canSpeak: boolean }> = {
  'goblin-scout': { temperament: 'cunning', canSpeak: true },
  'hobgoblin-soldier': { temperament: 'disciplined', canSpeak: true },
  'bandit-thug': { temperament: 'aggressive', canSpeak: true },
  'cultist-acolyte': { temperament: 'cautious', canSpeak: true },
  'kobold-skirmisher': { temperament: 'skittish', canSpeak: true },
  'wyrmling-drake': { temperament: 'territorial', canSpeak: true },
  'zombie-shambler': { temperament: 'mindless', canSpeak: false },
  'skeleton-archer': { temperament: 'mindless', canSpeak: false },
  'imp-familiar': { temperament: 'cunning', canSpeak: true },
  'lesser-demon-brute': { temperament: 'aggressive', canSpeak: true },
  'dire-wolf': { temperament: 'territorial', canSpeak: false },
  'giant-spider': { temperament: 'aggressive', canSpeak: false },
  'fire-elemental-spark': { temperament: 'aggressive', canSpeak: false },
  'water-elemental-wisp': { temperament: 'territorial', canSpeak: false },
  'stone-golem': { temperament: 'mindless', canSpeak: false },
  'animated-armor': { temperament: 'mindless', canSpeak: false }
}

function withBehavior(
  seed: Omit<CreateCatalogCreatureInput, 'temperament' | 'canSpeak'>
): CreateCatalogCreatureInput {
  const behavior = CREATURE_BEHAVIOR[seed.key]
  if (!behavior) {
    throw new Error(`Missing creature behavior for ${seed.key}`)
  }
  return { ...seed, ...behavior }
}

/**
 * Creature/enemy preseed dataset v1. Representative coverage across every
 * taxonomy bucket in src/shared/catalogTaxonomy.ts (TAXONOMY_VERSION 1).
 */
export const CREATURE_SEEDS_V1: CreateCatalogCreatureInput[] = [
  withBehavior({
    key: 'goblin-scout',
    name: 'Goblin Scout',
    archetypeHint: 'rogue',
    levelMin: 1,
    levelMax: 3,
    hp: 7,
    ac: 14,
    abilities: { body: 8, agility: 14, mind: 10, presence: 8 },
    resistances: {},
    damageTypes: ['physical'],
    tags: ['raider', 'ranged'],
    buckets: ['goblinoid'],
    source: 'seed',
    version: 1
  }),
  withBehavior({
    key: 'hobgoblin-soldier',
    name: 'Hobgoblin Soldier',
    archetypeHint: 'fighter',
    levelMin: 2,
    levelMax: 5,
    hp: 16,
    ac: 16,
    abilities: { body: 14, agility: 12, mind: 10, presence: 10 },
    resistances: {},
    damageTypes: ['physical'],
    tags: ['disciplined', 'melee'],
    buckets: ['goblinoid'],
    source: 'seed',
    version: 1
  }),
  withBehavior({
    key: 'bandit-thug',
    name: 'Bandit Thug',
    archetypeHint: 'fighter',
    levelMin: 1,
    levelMax: 3,
    hp: 11,
    ac: 12,
    abilities: { body: 12, agility: 11, mind: 9, presence: 9 },
    resistances: {},
    damageTypes: ['physical'],
    tags: ['mundane', 'melee'],
    buckets: ['humanoid'],
    source: 'seed',
    version: 1
  }),
  withBehavior({
    key: 'cultist-acolyte',
    name: 'Cultist Acolyte',
    archetypeHint: 'cleric',
    levelMin: 1,
    levelMax: 4,
    hp: 9,
    ac: 11,
    abilities: { body: 9, agility: 10, mind: 11, presence: 13 },
    resistances: {},
    damageTypes: ['arcane'],
    tags: ['caster', 'support'],
    buckets: ['humanoid'],
    source: 'seed',
    version: 1
  }),
  withBehavior({
    key: 'kobold-skirmisher',
    name: 'Kobold Skirmisher',
    archetypeHint: 'rogue',
    levelMin: 1,
    levelMax: 2,
    hp: 5,
    ac: 13,
    abilities: { body: 8, agility: 15, mind: 9, presence: 8 },
    resistances: {},
    damageTypes: ['physical'],
    tags: ['pack-tactics', 'ranged'],
    buckets: ['dragonkin', 'goblinoid'],
    source: 'seed',
    version: 1
  }),
  withBehavior({
    key: 'wyrmling-drake',
    name: 'Wyrmling Drake',
    archetypeHint: 'ranger',
    levelMin: 4,
    levelMax: 8,
    hp: 32,
    ac: 17,
    abilities: { body: 16, agility: 12, mind: 10, presence: 12 },
    resistances: { fire: 'resistant' },
    damageTypes: ['fire', 'physical'],
    tags: ['flying', 'breath-attack'],
    buckets: ['dragonkin'],
    source: 'seed',
    version: 1
  }),
  withBehavior({
    key: 'zombie-shambler',
    name: 'Zombie Shambler',
    levelMin: 1,
    levelMax: 3,
    hp: 14,
    ac: 8,
    abilities: { body: 13, agility: 6, mind: 4, presence: 4 },
    resistances: { poison: 'resistant' },
    damageTypes: ['physical'],
    tags: ['slow', 'undying'],
    buckets: ['undead'],
    source: 'seed',
    version: 1
  }),
  withBehavior({
    key: 'skeleton-archer',
    name: 'Skeleton Archer',
    archetypeHint: 'ranger',
    levelMin: 1,
    levelMax: 4,
    hp: 9,
    ac: 13,
    abilities: { body: 10, agility: 14, mind: 8, presence: 6 },
    resistances: { poison: 'resistant' },
    damageTypes: ['physical'],
    tags: ['ranged', 'undying'],
    buckets: ['undead'],
    source: 'seed',
    version: 1
  }),
  withBehavior({
    key: 'imp-familiar',
    name: 'Imp Familiar',
    archetypeHint: 'mage',
    levelMin: 2,
    levelMax: 5,
    hp: 8,
    ac: 14,
    abilities: { body: 8, agility: 14, mind: 12, presence: 12 },
    resistances: { fire: 'resistant' },
    damageTypes: ['fire', 'poison'],
    tags: ['flying', 'caster'],
    buckets: ['fiend'],
    source: 'seed',
    version: 1
  }),
  withBehavior({
    key: 'lesser-demon-brute',
    name: 'Lesser Demon Brute',
    archetypeHint: 'fighter',
    levelMin: 4,
    levelMax: 9,
    hp: 38,
    ac: 15,
    abilities: { body: 17, agility: 10, mind: 8, presence: 10 },
    resistances: { fire: 'resistant', physical: 'resistant' },
    damageTypes: ['physical', 'fire'],
    tags: ['brute', 'melee'],
    buckets: ['fiend'],
    source: 'seed',
    version: 1
  }),
  withBehavior({
    key: 'dire-wolf',
    name: 'Dire Wolf',
    levelMin: 1,
    levelMax: 4,
    hp: 13,
    ac: 13,
    abilities: { body: 13, agility: 15, mind: 6, presence: 7 },
    resistances: {},
    damageTypes: ['physical'],
    tags: ['pack-hunter', 'melee'],
    buckets: ['beast'],
    source: 'seed',
    version: 1
  }),
  withBehavior({
    key: 'giant-spider',
    name: 'Giant Spider',
    levelMin: 2,
    levelMax: 6,
    hp: 18,
    ac: 14,
    abilities: { body: 12, agility: 16, mind: 4, presence: 4 },
    resistances: { poison: 'resistant' },
    damageTypes: ['poison', 'physical'],
    tags: ['venomous', 'ambush'],
    buckets: ['beast'],
    source: 'seed',
    version: 1
  }),
  withBehavior({
    key: 'fire-elemental-spark',
    name: 'Fire Elemental Spark',
    levelMin: 3,
    levelMax: 7,
    hp: 22,
    ac: 15,
    abilities: { body: 14, agility: 13, mind: 6, presence: 8 },
    resistances: { fire: 'resistant', cold: 'vulnerable' },
    damageTypes: ['fire'],
    tags: ['elemental', 'burning'],
    buckets: ['elemental'],
    source: 'seed',
    version: 1
  }),
  withBehavior({
    key: 'water-elemental-wisp',
    name: 'Water Elemental Wisp',
    levelMin: 3,
    levelMax: 7,
    hp: 24,
    ac: 14,
    abilities: { body: 13, agility: 12, mind: 8, presence: 8 },
    resistances: { fire: 'resistant' },
    damageTypes: ['cold'],
    tags: ['elemental', 'engulf'],
    buckets: ['elemental'],
    source: 'seed',
    version: 1
  }),
  withBehavior({
    key: 'stone-golem',
    name: 'Stone Golem',
    archetypeHint: 'fighter',
    levelMin: 6,
    levelMax: 12,
    hp: 60,
    ac: 18,
    abilities: { body: 18, agility: 6, mind: 4, presence: 4 },
    resistances: { physical: 'resistant', poison: 'resistant' },
    damageTypes: ['physical'],
    tags: ['slow', 'construct'],
    buckets: ['construct'],
    source: 'seed',
    version: 1
  }),
  withBehavior({
    key: 'animated-armor',
    name: 'Animated Armor',
    archetypeHint: 'fighter',
    levelMin: 2,
    levelMax: 5,
    hp: 20,
    ac: 16,
    abilities: { body: 14, agility: 10, mind: 4, presence: 4 },
    resistances: { poison: 'resistant' },
    damageTypes: ['physical'],
    tags: ['mindless', 'construct'],
    buckets: ['construct'],
    source: 'seed',
    version: 1
  })
]
