import type { Temperament } from '../../../shared/alignment/types'
import type { CreateCatalogCreatureInput } from '../types'

const CREATURE_BEHAVIOR: Record<string, { temperament: Temperament; canSpeak: boolean }> = {
  'goblin-scout': { temperament: 'cunning', canSpeak: true },
  'hobgoblin-soldier': { temperament: 'disciplined', canSpeak: true },
  'bugbear-ambusher': { temperament: 'cunning', canSpeak: true },
  'goblin-boss': { temperament: 'aggressive', canSpeak: true },
  'hobgoblin-captain': { temperament: 'disciplined', canSpeak: true },
  'bugbear-chief': { temperament: 'aggressive', canSpeak: true },
  'bandit-thug': { temperament: 'aggressive', canSpeak: true },
  'cultist-acolyte': { temperament: 'cautious', canSpeak: true },
  'orc-raider': { temperament: 'aggressive', canSpeak: true },
  'gnoll-hunter': { temperament: 'aggressive', canSpeak: true },
  'tribal-berserker': { temperament: 'aggressive', canSpeak: true },
  'assassin': { temperament: 'cunning', canSpeak: true },
  'kobold-skirmisher': { temperament: 'skittish', canSpeak: true },
  'wyrmling-drake': { temperament: 'territorial', canSpeak: true },
  'kobold-dragonshield': { temperament: 'disciplined', canSpeak: true },
  'black-wyrmling': { temperament: 'territorial', canSpeak: true },
  'white-wyrmling': { temperament: 'territorial', canSpeak: true },
  'pseudodragon': { temperament: 'curious', canSpeak: false },
  'zombie-shambler': { temperament: 'mindless', canSpeak: false },
  'skeleton-archer': { temperament: 'mindless', canSpeak: false },
  'ghoul-scavenger': { temperament: 'aggressive', canSpeak: false },
  'wight-warrior': { temperament: 'aggressive', canSpeak: true },
  'specter-shade': { temperament: 'aggressive', canSpeak: false },
  'mummy-guardian': { temperament: 'disciplined', canSpeak: false },
  'imp-familiar': { temperament: 'cunning', canSpeak: true },
  'lesser-demon-brute': { temperament: 'aggressive', canSpeak: true },
  'quasit-trickster': { temperament: 'cunning', canSpeak: true },
  'hell-hound': { temperament: 'aggressive', canSpeak: false },
  'dretch-demon': { temperament: 'aggressive', canSpeak: true },
  'bearded-devil': { temperament: 'disciplined', canSpeak: true },
  'dire-wolf': { temperament: 'territorial', canSpeak: false },
  'giant-spider': { temperament: 'aggressive', canSpeak: false },
  'brown-bear': { temperament: 'territorial', canSpeak: false },
  'owlbear': { temperament: 'aggressive', canSpeak: false },
  'giant-rat': { temperament: 'skittish', canSpeak: false },
  'stirge': { temperament: 'aggressive', canSpeak: false },
  'fire-elemental-spark': { temperament: 'aggressive', canSpeak: false },
  'water-elemental-wisp': { temperament: 'territorial', canSpeak: false },
  'air-elemental-breeze': { temperament: 'territorial', canSpeak: false },
  'earth-elemental-clod': { temperament: 'territorial', canSpeak: false },
  'magmin-spark': { temperament: 'curious', canSpeak: true },
  'dust-mephit': { temperament: 'skittish', canSpeak: true },
  'stone-golem': { temperament: 'mindless', canSpeak: false },
  'animated-armor': { temperament: 'mindless', canSpeak: false },
  'clay-golem': { temperament: 'mindless', canSpeak: false },
  'flying-sword': { temperament: 'mindless', canSpeak: false },
  'shield-guardian': { temperament: 'disciplined', canSpeak: false },
  'helmed-horror': { temperament: 'disciplined', canSpeak: false }
}

function withBehavior(
  seed: Omit<CreateCatalogCreatureInput, 'temperament' | 'canSpeak'>
): CreateCatalogCreatureInput {
  const behavior = CREATURE_BEHAVIOR[seed.key]
  if (!behavior) {
    throw new Error(`Missing creature behavior for ${seed.key}`)
  }
  return { ...seed, ...behavior }
}

/**
 * Creature/enemy preseed dataset v1. Representative coverage across every
 * taxonomy bucket in src/shared/catalogTaxonomy.ts (TAXONOMY_VERSION 1).
 * Expanded to 48 conventional TTRPG foes (3× the original 16-entry roster).
 */
export const CREATURE_SEEDS_V1: CreateCatalogCreatureInput[] = [
  withBehavior({
    key: 'goblin-scout',
    name: 'Goblin Scout',
    archetypeHint: 'rogue',
    levelMin: 1,
    levelMax: 3,
    hp: 7,
    ac: 14,
    abilities: { body: 8, agility: 14, mind: 10, presence: 8 },
    resistances: {},
    damageTypes: ['physical'],
    tags: ['raider', 'ranged'],
    buckets: ['goblinoid'],
    source: 'seed',
    version: 1
  }),
  withBehavior({
    key: 'hobgoblin-soldier',
    name: 'Hobgoblin Soldier',
    archetypeHint: 'fighter',
    levelMin: 2,
    levelMax: 5,
    hp: 16,
    ac: 16,
    abilities: { body: 14, agility: 12, mind: 10, presence: 10 },
    resistances: {},
    damageTypes: ['physical'],
    tags: ['disciplined', 'melee'],
    buckets: ['goblinoid'],
    source: 'seed',
    version: 1
  }),
  withBehavior({
    key: 'bugbear-ambusher',
    name: 'Bugbear Ambusher',
    archetypeHint: 'rogue',
    levelMin: 2,
    levelMax: 5,
    hp: 27,
    ac: 14,
    abilities: { body: 15, agility: 14, mind: 10, presence: 9 },
    resistances: {},
    damageTypes: ['physical'],
    tags: ['ambush', 'melee'],
    buckets: ['goblinoid'],
    source: 'seed',
    version: 1
  }),
  withBehavior({
    key: 'goblin-boss',
    name: 'Goblin Boss',
    archetypeHint: 'fighter',
    levelMin: 2,
    levelMax: 4,
    hp: 21,
    ac: 15,
    abilities: { body: 12, agility: 14, mind: 10, presence: 12 },
    resistances: {},
    damageTypes: ['physical'],
    tags: ['leader', 'melee'],
    buckets: ['goblinoid'],
    source: 'seed',
    version: 1
  }),
  withBehavior({
    key: 'hobgoblin-captain',
    name: 'Hobgoblin Captain',
    archetypeHint: 'fighter',
    levelMin: 4,
    levelMax: 8,
    hp: 39,
    ac: 17,
    abilities: { body: 15, agility: 13, mind: 12, presence: 13 },
    resistances: {},
    damageTypes: ['physical'],
    tags: ['leader', 'disciplined'],
    buckets: ['goblinoid'],
    source: 'seed',
    version: 1
  }),
  withBehavior({
    key: 'bugbear-chief',
    name: 'Bugbear Chief',
    archetypeHint: 'fighter',
    levelMin: 4,
    levelMax: 8,
    hp: 45,
    ac: 15,
    abilities: { body: 17, agility: 14, mind: 11, presence: 12 },
    resistances: {},
    damageTypes: ['physical'],
    tags: ['leader', 'brute'],
    buckets: ['goblinoid'],
    source: 'seed',
    version: 1
  }),
  withBehavior({
    key: 'bandit-thug',
    name: 'Bandit Thug',
    archetypeHint: 'fighter',
    levelMin: 1,
    levelMax: 3,
    hp: 11,
    ac: 12,
    abilities: { body: 12, agility: 11, mind: 9, presence: 9 },
    resistances: {},
    damageTypes: ['physical'],
    tags: ['mundane', 'melee'],
    buckets: ['humanoid'],
    source: 'seed',
    version: 1
  }),
  withBehavior({
    key: 'cultist-acolyte',
    name: 'Cultist Acolyte',
    archetypeHint: 'cleric',
    levelMin: 1,
    levelMax: 4,
    hp: 9,
    ac: 11,
    abilities: { body: 9, agility: 10, mind: 11, presence: 13 },
    resistances: {},
    damageTypes: ['arcane'],
    tags: ['caster', 'support'],
    buckets: ['humanoid'],
    source: 'seed',
    version: 1
  }),
  withBehavior({
    key: 'orc-raider',
    name: 'Orc Raider',
    archetypeHint: 'fighter',
    levelMin: 1,
    levelMax: 4,
    hp: 15,
    ac: 13,
    abilities: { body: 16, agility: 12, mind: 9, presence: 10 },
    resistances: {},
    damageTypes: ['physical'],
    tags: ['raider', 'melee'],
    buckets: ['humanoid'],
    source: 'seed',
    version: 1
  }),
  withBehavior({
    key: 'gnoll-hunter',
    name: 'Gnoll Hunter',
    archetypeHint: 'ranger',
    levelMin: 1,
    levelMax: 4,
    hp: 18,
    ac: 13,
    abilities: { body: 14, agility: 14, mind: 8, presence: 8 },
    resistances: {},
    damageTypes: ['physical'],
    tags: ['pack-hunter', 'ranged'],
    buckets: ['humanoid'],
    source: 'seed',
    version: 1
  }),
  withBehavior({
    key: 'tribal-berserker',
    name: 'Tribal Berserker',
    archetypeHint: 'fighter',
    levelMin: 2,
    levelMax: 5,
    hp: 22,
    ac: 12,
    abilities: { body: 16, agility: 12, mind: 9, presence: 10 },
    resistances: {},
    damageTypes: ['physical'],
    tags: ['berserk', 'melee'],
    buckets: ['humanoid'],
    source: 'seed',
    version: 1
  }),
  withBehavior({
    key: 'assassin',
    name: 'Assassin',
    archetypeHint: 'rogue',
    levelMin: 5,
    levelMax: 10,
    hp: 38,
    ac: 15,
    abilities: { body: 11, agility: 16, mind: 13, presence: 12 },
    resistances: { poison: 'resistant' },
    damageTypes: ['physical', 'poison'],
    tags: ['ambush', 'poison'],
    buckets: ['humanoid'],
    source: 'seed',
    version: 1
  }),
  withBehavior({
    key: 'kobold-skirmisher',
    name: 'Kobold Skirmisher',
    archetypeHint: 'rogue',
    levelMin: 1,
    levelMax: 2,
    hp: 5,
    ac: 13,
    abilities: { body: 8, agility: 15, mind: 9, presence: 8 },
    resistances: {},
    damageTypes: ['physical'],
    tags: ['pack-tactics', 'ranged'],
    buckets: ['dragonkin', 'goblinoid'],
    source: 'seed',
    version: 1
  }),
  withBehavior({
    key: 'wyrmling-drake',
    name: 'Wyrmling Drake',
    archetypeHint: 'ranger',
    levelMin: 4,
    levelMax: 8,
    hp: 32,
    ac: 17,
    abilities: { body: 16, agility: 12, mind: 10, presence: 12 },
    resistances: { fire: 'resistant' },
    damageTypes: ['fire', 'physical'],
    tags: ['flying', 'breath-attack'],
    buckets: ['dragonkin'],
    source: 'seed',
    version: 1
  }),
  withBehavior({
    key: 'kobold-dragonshield',
    name: 'Kobold Dragonshield',
    archetypeHint: 'fighter',
    levelMin: 1,
    levelMax: 3,
    hp: 12,
    ac: 15,
    abilities: { body: 12, agility: 14, mind: 9, presence: 10 },
    resistances: {},
    damageTypes: ['physical'],
    tags: ['pack-tactics', 'melee'],
    buckets: ['dragonkin', 'goblinoid'],
    source: 'seed',
    version: 1
  }),
  withBehavior({
    key: 'black-wyrmling',
    name: 'Black Dragon Wyrmling',
    archetypeHint: 'ranger',
    levelMin: 3,
    levelMax: 6,
    hp: 33,
    ac: 17,
    abilities: { body: 15, agility: 14, mind: 10, presence: 11 },
    resistances: { poison: 'resistant' },
    damageTypes: ['poison', 'physical'],
    tags: ['flying', 'breath-attack'],
    buckets: ['dragonkin'],
    source: 'seed',
    version: 1
  }),
  withBehavior({
    key: 'white-wyrmling',
    name: 'White Dragon Wyrmling',
    archetypeHint: 'ranger',
    levelMin: 3,
    levelMax: 6,
    hp: 32,
    ac: 16,
    abilities: { body: 14, agility: 12, mind: 8, presence: 10 },
    resistances: { cold: 'resistant' },
    damageTypes: ['cold', 'physical'],
    tags: ['flying', 'breath-attack'],
    buckets: ['dragonkin'],
    source: 'seed',
    version: 1
  }),
  withBehavior({
    key: 'pseudodragon',
    name: 'Pseudodragon',
    levelMin: 1,
    levelMax: 3,
    hp: 7,
    ac: 13,
    abilities: { body: 8, agility: 15, mind: 10, presence: 12 },
    resistances: {},
    damageTypes: ['poison', 'physical'],
    tags: ['flying', 'familiar'],
    buckets: ['dragonkin'],
    source: 'seed',
    version: 1
  }),
  withBehavior({
    key: 'zombie-shambler',
    name: 'Zombie Shambler',
    levelMin: 1,
    levelMax: 3,
    hp: 14,
    ac: 8,
    abilities: { body: 13, agility: 6, mind: 4, presence: 4 },
    resistances: { poison: 'resistant' },
    damageTypes: ['physical'],
    tags: ['slow', 'undying'],
    buckets: ['undead'],
    source: 'seed',
    version: 1
  }),
  withBehavior({
    key: 'skeleton-archer',
    name: 'Skeleton Archer',
    archetypeHint: 'ranger',
    levelMin: 1,
    levelMax: 4,
    hp: 9,
    ac: 13,
    abilities: { body: 10, agility: 14, mind: 8, presence: 6 },
    resistances: { poison: 'resistant' },
    damageTypes: ['physical'],
    tags: ['ranged', 'undying'],
    buckets: ['undead'],
    source: 'seed',
    version: 1
  }),
  withBehavior({
    key: 'ghoul-scavenger',
    name: 'Ghoul Scavenger',
    levelMin: 1,
    levelMax: 4,
    hp: 22,
    ac: 12,
    abilities: { body: 13, agility: 15, mind: 8, presence: 8 },
    resistances: { poison: 'resistant' },
    damageTypes: ['physical'],
    tags: ['paralyzing', 'melee'],
    buckets: ['undead'],
    source: 'seed',
    version: 1
  }),
  withBehavior({
    key: 'wight-warrior',
    name: 'Wight Warrior',
    archetypeHint: 'fighter',
    levelMin: 3,
    levelMax: 7,
    hp: 45,
    ac: 14,
    abilities: { body: 15, agility: 14, mind: 10, presence: 13 },
    resistances: { poison: 'resistant', physical: 'resistant' },
    damageTypes: ['physical'],
    tags: ['life-drain', 'melee'],
    buckets: ['undead'],
    source: 'seed',
    version: 1
  }),
  withBehavior({
    key: 'specter-shade',
    name: 'Specter Shade',
    levelMin: 2,
    levelMax: 5,
    hp: 22,
    ac: 12,
    abilities: { body: 6, agility: 14, mind: 10, presence: 11 },
    resistances: { poison: 'resistant', physical: 'resistant' },
    damageTypes: ['arcane'],
    tags: ['incorporeal', 'life-drain'],
    buckets: ['undead'],
    source: 'seed',
    version: 1
  }),
  withBehavior({
    key: 'mummy-guardian',
    name: 'Mummy Guardian',
    archetypeHint: 'fighter',
    levelMin: 4,
    levelMax: 8,
    hp: 58,
    ac: 11,
    abilities: { body: 16, agility: 8, mind: 8, presence: 14 },
    resistances: { poison: 'resistant', fire: 'vulnerable' },
    damageTypes: ['physical'],
    tags: ['curse', 'slow'],
    buckets: ['undead'],
    source: 'seed',
    version: 1
  }),
  withBehavior({
    key: 'imp-familiar',
    name: 'Imp Familiar',
    archetypeHint: 'mage',
    levelMin: 2,
    levelMax: 5,
    hp: 8,
    ac: 14,
    abilities: { body: 8, agility: 14, mind: 12, presence: 12 },
    resistances: { fire: 'resistant' },
    damageTypes: ['fire', 'poison'],
    tags: ['flying', 'caster'],
    buckets: ['fiend'],
    source: 'seed',
    version: 1
  }),
  withBehavior({
    key: 'lesser-demon-brute',
    name: 'Lesser Demon Brute',
    archetypeHint: 'fighter',
    levelMin: 4,
    levelMax: 9,
    hp: 38,
    ac: 15,
    abilities: { body: 17, agility: 10, mind: 8, presence: 10 },
    resistances: { fire: 'resistant', physical: 'resistant' },
    damageTypes: ['physical', 'fire'],
    tags: ['brute', 'melee'],
    buckets: ['fiend'],
    source: 'seed',
    version: 1
  }),
  withBehavior({
    key: 'quasit-trickster',
    name: 'Quasit Trickster',
    archetypeHint: 'rogue',
    levelMin: 1,
    levelMax: 3,
    hp: 7,
    ac: 13,
    abilities: { body: 7, agility: 15, mind: 10, presence: 10 },
    resistances: { fire: 'resistant', poison: 'resistant' },
    damageTypes: ['poison', 'physical'],
    tags: ['shapechanger', 'familiar'],
    buckets: ['fiend'],
    source: 'seed',
    version: 1
  }),
  withBehavior({
    key: 'hell-hound',
    name: 'Hell Hound',
    levelMin: 3,
    levelMax: 6,
    hp: 45,
    ac: 15,
    abilities: { body: 15, agility: 14, mind: 8, presence: 8 },
    resistances: { fire: 'resistant' },
    damageTypes: ['fire', 'physical'],
    tags: ['pack-hunter', 'breath-attack'],
    buckets: ['fiend', 'beast'],
    source: 'seed',
    version: 1
  }),
  withBehavior({
    key: 'dretch-demon',
    name: 'Dretch Demon',
    levelMin: 1,
    levelMax: 3,
    hp: 18,
    ac: 11,
    abilities: { body: 12, agility: 11, mind: 6, presence: 8 },
    resistances: { fire: 'resistant', poison: 'resistant' },
    damageTypes: ['physical'],
    tags: ['swarm', 'melee'],
    buckets: ['fiend'],
    source: 'seed',
    version: 1
  }),
  withBehavior({
    key: 'bearded-devil',
    name: 'Bearded Devil',
    archetypeHint: 'fighter',
    levelMin: 4,
    levelMax: 8,
    hp: 52,
    ac: 13,
    abilities: { body: 16, agility: 14, mind: 10, presence: 12 },
    resistances: { fire: 'resistant', poison: 'resistant' },
    damageTypes: ['physical', 'poison'],
    tags: ['disciplined', 'melee'],
    buckets: ['fiend'],
    source: 'seed',
    version: 1
  }),
  withBehavior({
    key: 'dire-wolf',
    name: 'Dire Wolf',
    levelMin: 1,
    levelMax: 4,
    hp: 13,
    ac: 13,
    abilities: { body: 13, agility: 15, mind: 6, presence: 7 },
    resistances: {},
    damageTypes: ['physical'],
    tags: ['pack-hunter', 'melee'],
    buckets: ['beast'],
    source: 'seed',
    version: 1
  }),
  withBehavior({
    key: 'giant-spider',
    name: 'Giant Spider',
    levelMin: 2,
    levelMax: 6,
    hp: 18,
    ac: 14,
    abilities: { body: 12, agility: 16, mind: 4, presence: 4 },
    resistances: { poison: 'resistant' },
    damageTypes: ['poison', 'physical'],
    tags: ['venomous', 'ambush'],
    buckets: ['beast'],
    source: 'seed',
    version: 1
  }),
  withBehavior({
    key: 'brown-bear',
    name: 'Brown Bear',
    levelMin: 1,
    levelMax: 4,
    hp: 34,
    ac: 11,
    abilities: { body: 17, agility: 10, mind: 4, presence: 8 },
    resistances: {},
    damageTypes: ['physical'],
    tags: ['brute', 'melee'],
    buckets: ['beast'],
    source: 'seed',
    version: 1
  }),
  withBehavior({
    key: 'owlbear',
    name: 'Owlbear',
    levelMin: 3,
    levelMax: 7,
    hp: 59,
    ac: 13,
    abilities: { body: 18, agility: 12, mind: 4, presence: 8 },
    resistances: {},
    damageTypes: ['physical'],
    tags: ['brute', 'ambush'],
    buckets: ['beast'],
    source: 'seed',
    version: 1
  }),
  withBehavior({
    key: 'giant-rat',
    name: 'Giant Rat',
    levelMin: 1,
    levelMax: 2,
    hp: 7,
    ac: 12,
    abilities: { body: 8, agility: 15, mind: 4, presence: 4 },
    resistances: {},
    damageTypes: ['physical'],
    tags: ['pack-hunter', 'disease'],
    buckets: ['beast'],
    source: 'seed',
    version: 1
  }),
  withBehavior({
    key: 'stirge',
    name: 'Stirge',
    levelMin: 1,
    levelMax: 2,
    hp: 2,
    ac: 14,
    abilities: { body: 6, agility: 16, mind: 2, presence: 4 },
    resistances: {},
    damageTypes: ['physical'],
    tags: ['flying', 'blood-drain'],
    buckets: ['beast'],
    source: 'seed',
    version: 1
  }),
  withBehavior({
    key: 'fire-elemental-spark',
    name: 'Fire Elemental Spark',
    levelMin: 3,
    levelMax: 7,
    hp: 22,
    ac: 15,
    abilities: { body: 14, agility: 13, mind: 6, presence: 8 },
    resistances: { fire: 'resistant', cold: 'vulnerable' },
    damageTypes: ['fire'],
    tags: ['elemental', 'burning'],
    buckets: ['elemental'],
    source: 'seed',
    version: 1
  }),
  withBehavior({
    key: 'water-elemental-wisp',
    name: 'Water Elemental Wisp',
    levelMin: 3,
    levelMax: 7,
    hp: 24,
    ac: 14,
    abilities: { body: 13, agility: 12, mind: 8, presence: 8 },
    resistances: { fire: 'resistant' },
    damageTypes: ['cold'],
    tags: ['elemental', 'engulf'],
    buckets: ['elemental'],
    source: 'seed',
    version: 1
  }),
  withBehavior({
    key: 'air-elemental-breeze',
    name: 'Air Elemental Breeze',
    levelMin: 3,
    levelMax: 7,
    hp: 28,
    ac: 15,
    abilities: { body: 12, agility: 18, mind: 8, presence: 8 },
    resistances: { physical: 'resistant' },
    damageTypes: ['physical'],
    tags: ['elemental', 'flying'],
    buckets: ['elemental'],
    source: 'seed',
    version: 1
  }),
  withBehavior({
    key: 'earth-elemental-clod',
    name: 'Earth Elemental Clod',
    levelMin: 3,
    levelMax: 7,
    hp: 40,
    ac: 17,
    abilities: { body: 18, agility: 8, mind: 6, presence: 8 },
    resistances: { physical: 'resistant' },
    damageTypes: ['physical'],
    tags: ['elemental', 'brute'],
    buckets: ['elemental'],
    source: 'seed',
    version: 1
  }),
  withBehavior({
    key: 'magmin-spark',
    name: 'Magmin Spark',
    levelMin: 1,
    levelMax: 3,
    hp: 9,
    ac: 14,
    abilities: { body: 10, agility: 14, mind: 8, presence: 10 },
    resistances: { fire: 'resistant' },
    damageTypes: ['fire'],
    tags: ['elemental', 'burning'],
    buckets: ['elemental'],
    source: 'seed',
    version: 1
  }),
  withBehavior({
    key: 'dust-mephit',
    name: 'Dust Mephit',
    levelMin: 1,
    levelMax: 3,
    hp: 17,
    ac: 12,
    abilities: { body: 8, agility: 14, mind: 9, presence: 10 },
    resistances: {},
    damageTypes: ['physical'],
    tags: ['flying', 'blinding'],
    buckets: ['elemental'],
    source: 'seed',
    version: 1
  }),
  withBehavior({
    key: 'stone-golem',
    name: 'Stone Golem',
    archetypeHint: 'fighter',
    levelMin: 6,
    levelMax: 12,
    hp: 60,
    ac: 18,
    abilities: { body: 18, agility: 6, mind: 4, presence: 4 },
    resistances: { physical: 'resistant', poison: 'resistant' },
    damageTypes: ['physical'],
    tags: ['slow', 'construct'],
    buckets: ['construct'],
    source: 'seed',
    version: 1
  }),
  withBehavior({
    key: 'animated-armor',
    name: 'Animated Armor',
    archetypeHint: 'fighter',
    levelMin: 2,
    levelMax: 5,
    hp: 20,
    ac: 16,
    abilities: { body: 14, agility: 10, mind: 4, presence: 4 },
    resistances: { poison: 'resistant' },
    damageTypes: ['physical'],
    tags: ['mindless', 'construct'],
    buckets: ['construct'],
    source: 'seed',
    version: 1
  }),
  withBehavior({
    key: 'clay-golem',
    name: 'Clay Golem',
    archetypeHint: 'fighter',
    levelMin: 6,
    levelMax: 11,
    hp: 70,
    ac: 14,
    abilities: { body: 18, agility: 8, mind: 4, presence: 4 },
    resistances: { physical: 'resistant', poison: 'resistant', arcane: 'resistant' },
    damageTypes: ['physical'],
    tags: ['berserk', 'construct'],
    buckets: ['construct'],
    source: 'seed',
    version: 1
  }),
  withBehavior({
    key: 'flying-sword',
    name: 'Flying Sword',
    levelMin: 1,
    levelMax: 3,
    hp: 10,
    ac: 17,
    abilities: { body: 12, agility: 15, mind: 2, presence: 2 },
    resistances: { poison: 'resistant' },
    damageTypes: ['physical'],
    tags: ['flying', 'construct'],
    buckets: ['construct'],
    source: 'seed',
    version: 1
  }),
  withBehavior({
    key: 'shield-guardian',
    name: 'Shield Guardian',
    archetypeHint: 'fighter',
    levelMin: 5,
    levelMax: 10,
    hp: 75,
    ac: 17,
    abilities: { body: 18, agility: 10, mind: 8, presence: 10 },
    resistances: { poison: 'resistant' },
    damageTypes: ['physical'],
    tags: ['guardian', 'construct'],
    buckets: ['construct'],
    source: 'seed',
    version: 1
  }),
  withBehavior({
    key: 'helmed-horror',
    name: 'Helmed Horror',
    archetypeHint: 'fighter',
    levelMin: 4,
    levelMax: 8,
    hp: 60,
    ac: 20,
    abilities: { body: 16, agility: 13, mind: 10, presence: 10 },
    resistances: { poison: 'resistant', fire: 'resistant', cold: 'resistant' },
    damageTypes: ['physical'],
    tags: ['flying', 'construct'],
    buckets: ['construct'],
    source: 'seed',
    version: 1
  })
]
