import type { CreateCatalogSpellInput } from '../types'

/**
 * Spell/ability preseed dataset v1. Core coverage for early gameplay loops
 * across all five seed archetypes — damage, healing, buff, debuff, control, and
 * utility — with bucket tags applied where a spell is thematically tied to an
 * opposing creature family (e.g. holy spells tagged against undead).
 */
export const SPELL_SEEDS_V1: CreateCatalogSpellInput[] = [
  {
    key: 'firebolt',
    name: 'Firebolt',
    effectType: 'damage',
    range: 'ranged',
    cost: 1,
    archetypeHint: 'mage',
    tags: ['fire', 'single-target'],
    buckets: ['elemental'],
    constraints: { requiresArchetype: ['mage'], minLevel: 1 },
    source: 'seed',
    version: 1
  },
  {
    key: 'arcane-bolt',
    name: 'Arcane Bolt',
    effectType: 'damage',
    range: 'ranged',
    cost: 1,
    archetypeHint: 'mage',
    tags: ['arcane', 'single-target'],
    buckets: ['humanoid'],
    constraints: { requiresArchetype: ['mage'], minLevel: 1 },
    source: 'seed',
    version: 1
  },
  {
    key: 'frost-shard',
    name: 'Frost Shard',
    effectType: 'damage',
    range: 'ranged',
    cost: 2,
    archetypeHint: 'mage',
    tags: ['cold', 'area'],
    buckets: ['elemental'],
    constraints: { requiresArchetype: ['mage'], minLevel: 3 },
    source: 'seed',
    version: 1
  },
  {
    key: 'turn-undead',
    name: 'Turn Undead',
    effectType: 'control',
    range: 'medium',
    cost: 2,
    archetypeHint: 'cleric',
    tags: ['holy', 'area'],
    buckets: ['undead'],
    constraints: { requiresArchetype: ['cleric'], minLevel: 2 },
    source: 'seed',
    version: 1
  },
  {
    key: 'minor-heal',
    name: 'Minor Heal',
    effectType: 'healing',
    range: 'touch',
    cost: 1,
    archetypeHint: 'cleric',
    tags: ['support'],
    buckets: ['humanoid'],
    constraints: { requiresArchetype: ['cleric'], minLevel: 1 },
    source: 'seed',
    version: 1
  },
  {
    key: 'sacred-flame',
    name: 'Sacred Flame',
    effectType: 'damage',
    range: 'ranged',
    cost: 1,
    archetypeHint: 'cleric',
    tags: ['holy', 'single-target'],
    buckets: ['undead'],
    constraints: { requiresArchetype: ['cleric'], minLevel: 1 },
    source: 'seed',
    version: 1
  },
  {
    key: 'smite-fiend',
    name: 'Smite Fiend',
    effectType: 'damage',
    range: 'melee',
    cost: 1,
    archetypeHint: 'cleric',
    tags: ['holy', 'single-target'],
    buckets: ['fiend'],
    constraints: { requiresArchetype: ['cleric'], minLevel: 2 },
    source: 'seed',
    version: 1
  },
  {
    key: 'sneak-strike',
    name: 'Sneak Strike',
    effectType: 'damage',
    range: 'melee',
    cost: 1,
    archetypeHint: 'rogue',
    tags: ['precision', 'single-target'],
    buckets: ['humanoid'],
    constraints: { requiresArchetype: ['rogue'], minLevel: 1 },
    source: 'seed',
    version: 1
  },
  {
    key: 'shadow-step',
    name: 'Shadow Step',
    effectType: 'utility',
    range: 'self',
    cost: 1,
    archetypeHint: 'rogue',
    tags: ['mobility'],
    buckets: ['humanoid'],
    constraints: { requiresArchetype: ['rogue'], minLevel: 2 },
    source: 'seed',
    version: 1
  },
  {
    key: 'rallying-strike',
    name: 'Rallying Strike',
    effectType: 'damage',
    range: 'melee',
    cost: 1,
    archetypeHint: 'fighter',
    tags: ['single-target', 'morale'],
    buckets: ['humanoid'],
    constraints: { requiresArchetype: ['fighter'], minLevel: 1 },
    source: 'seed',
    version: 1
  },
  {
    key: 'shield-bash',
    name: 'Shield Bash',
    effectType: 'control',
    range: 'melee',
    cost: 1,
    archetypeHint: 'fighter',
    tags: ['stun', 'single-target'],
    buckets: ['construct'],
    constraints: { requiresArchetype: ['fighter'], minLevel: 2 },
    source: 'seed',
    version: 1
  },
  {
    key: 'beast-bond-strike',
    name: "Beast Bond Strike",
    effectType: 'damage',
    range: 'ranged',
    cost: 1,
    archetypeHint: 'ranger',
    tags: ['single-target', 'precision'],
    buckets: ['beast'],
    constraints: { requiresArchetype: ['ranger'], minLevel: 1 },
    source: 'seed',
    version: 1
  },
  {
    key: 'hunters-mark',
    name: "Hunter's Mark",
    effectType: 'utility',
    range: 'ranged',
    cost: 1,
    archetypeHint: 'ranger',
    tags: ['tracking'],
    buckets: ['beast', 'dragonkin'],
    constraints: { requiresArchetype: ['ranger'], minLevel: 1 },
    source: 'seed',
    version: 1
  },
  // --- Fighter starters (level 1) ---
  {
    key: 'war-cry',
    name: 'War Cry',
    effectType: 'buff',
    range: 'self',
    cost: 1,
    archetypeHint: 'fighter',
    tags: ['morale', 'single-target'],
    buckets: ['humanoid'],
    constraints: { requiresArchetype: ['fighter'], minLevel: 1 },
    source: 'seed',
    version: 1
  },
  {
    key: 'pressing-assault',
    name: 'Pressing Assault',
    effectType: 'damage',
    range: 'melee',
    cost: 1,
    archetypeHint: 'fighter',
    tags: ['single-target', 'pressure'],
    buckets: ['humanoid'],
    constraints: { requiresArchetype: ['fighter'], minLevel: 1 },
    source: 'seed',
    version: 1
  },
  {
    key: 'iron-stance',
    name: 'Iron Stance',
    effectType: 'buff',
    range: 'self',
    cost: 1,
    archetypeHint: 'fighter',
    tags: ['defense', 'single-target'],
    buckets: ['construct'],
    constraints: { requiresArchetype: ['fighter'], minLevel: 1 },
    source: 'seed',
    version: 1
  },
  {
    key: 'hamstring',
    name: 'Hamstring',
    effectType: 'debuff',
    range: 'melee',
    cost: 1,
    archetypeHint: 'fighter',
    tags: ['slow', 'single-target'],
    buckets: ['humanoid', 'beast'],
    constraints: { requiresArchetype: ['fighter'], minLevel: 1 },
    source: 'seed',
    version: 1
  },
  {
    key: 'taunting-shout',
    name: 'Taunting Shout',
    effectType: 'debuff',
    range: 'medium',
    cost: 1,
    archetypeHint: 'fighter',
    tags: ['taunt', 'area'],
    buckets: ['humanoid'],
    constraints: { requiresArchetype: ['fighter'], minLevel: 1 },
    source: 'seed',
    version: 1
  },
  // --- Rogue starters (level 1) ---
  {
    key: 'venom-stab',
    name: 'Venom Stab',
    effectType: 'damage',
    range: 'melee',
    cost: 1,
    archetypeHint: 'rogue',
    tags: ['poison', 'single-target'],
    buckets: ['humanoid', 'beast'],
    constraints: { requiresArchetype: ['rogue'], minLevel: 1 },
    source: 'seed',
    version: 1
  },
  {
    key: 'blur-step',
    name: 'Blur Step',
    effectType: 'buff',
    range: 'self',
    cost: 1,
    archetypeHint: 'rogue',
    tags: ['evasion', 'mobility'],
    buckets: ['humanoid'],
    constraints: { requiresArchetype: ['rogue'], minLevel: 1 },
    source: 'seed',
    version: 1
  },
  {
    key: 'dirt-in-eyes',
    name: 'Dirt in the Eyes',
    effectType: 'debuff',
    range: 'ranged',
    cost: 1,
    archetypeHint: 'rogue',
    tags: ['blind', 'single-target'],
    buckets: ['humanoid'],
    constraints: { requiresArchetype: ['rogue'], minLevel: 1 },
    source: 'seed',
    version: 1
  },
  {
    key: 'cheap-shot',
    name: 'Cheap Shot',
    effectType: 'damage',
    range: 'melee',
    cost: 1,
    archetypeHint: 'rogue',
    tags: ['precision', 'single-target'],
    buckets: ['humanoid'],
    constraints: { requiresArchetype: ['rogue'], minLevel: 1 },
    source: 'seed',
    version: 1
  },
  // --- Mage starters (level 1) ---
  {
    key: 'magic-missile',
    name: 'Magic Missile',
    effectType: 'damage',
    range: 'ranged',
    cost: 1,
    archetypeHint: 'mage',
    tags: ['arcane', 'single-target'],
    buckets: ['humanoid'],
    constraints: { requiresArchetype: ['mage'], minLevel: 1 },
    source: 'seed',
    version: 1
  },
  {
    key: 'shocking-grasp',
    name: 'Shocking Grasp',
    effectType: 'damage',
    range: 'melee',
    cost: 1,
    archetypeHint: 'mage',
    tags: ['lightning', 'single-target'],
    buckets: ['elemental', 'construct'],
    constraints: { requiresArchetype: ['mage'], minLevel: 1 },
    source: 'seed',
    version: 1
  },
  {
    key: 'mage-armor',
    name: 'Mage Armor',
    effectType: 'buff',
    range: 'self',
    cost: 1,
    archetypeHint: 'mage',
    tags: ['defense', 'arcane'],
    buckets: ['humanoid'],
    constraints: { requiresArchetype: ['mage'], minLevel: 1 },
    source: 'seed',
    version: 1
  },
  {
    key: 'ray-of-frost',
    name: 'Ray of Frost',
    effectType: 'debuff',
    range: 'ranged',
    cost: 1,
    archetypeHint: 'mage',
    tags: ['cold', 'slow', 'single-target'],
    buckets: ['elemental'],
    constraints: { requiresArchetype: ['mage'], minLevel: 1 },
    source: 'seed',
    version: 1
  },
  {
    key: 'chill-touch',
    name: 'Chill Touch',
    effectType: 'damage',
    range: 'melee',
    cost: 1,
    archetypeHint: 'mage',
    tags: ['cold', 'necrotic', 'single-target'],
    buckets: ['undead'],
    constraints: { requiresArchetype: ['mage'], minLevel: 1 },
    source: 'seed',
    version: 1
  },
  // --- Cleric starters (level 1) ---
  {
    key: 'bless',
    name: 'Bless',
    effectType: 'buff',
    range: 'medium',
    cost: 1,
    archetypeHint: 'cleric',
    tags: ['holy', 'support'],
    buckets: ['humanoid'],
    constraints: { requiresArchetype: ['cleric'], minLevel: 1 },
    source: 'seed',
    version: 1
  },
  {
    key: 'bane',
    name: 'Bane',
    effectType: 'debuff',
    range: 'ranged',
    cost: 1,
    archetypeHint: 'cleric',
    tags: ['holy', 'curse'],
    buckets: ['fiend', 'undead'],
    constraints: { requiresArchetype: ['cleric'], minLevel: 1 },
    source: 'seed',
    version: 1
  },
  {
    key: 'shield-of-faith',
    name: 'Shield of Faith',
    effectType: 'buff',
    range: 'self',
    cost: 1,
    archetypeHint: 'cleric',
    tags: ['holy', 'defense'],
    buckets: ['humanoid'],
    constraints: { requiresArchetype: ['cleric'], minLevel: 1 },
    source: 'seed',
    version: 1
  },
  {
    key: 'guiding-bolt',
    name: 'Guiding Bolt',
    effectType: 'damage',
    range: 'ranged',
    cost: 1,
    archetypeHint: 'cleric',
    tags: ['holy', 'single-target'],
    buckets: ['undead'],
    constraints: { requiresArchetype: ['cleric'], minLevel: 1 },
    source: 'seed',
    version: 1
  },
  // --- Ranger starters (level 1) ---
  {
    key: 'ensnaring-shot',
    name: 'Ensnaring Shot',
    effectType: 'control',
    range: 'ranged',
    cost: 1,
    archetypeHint: 'ranger',
    tags: ['restraint', 'single-target'],
    buckets: ['beast', 'humanoid'],
    constraints: { requiresArchetype: ['ranger'], minLevel: 1 },
    source: 'seed',
    version: 1
  },
  {
    key: 'thorn-volley',
    name: 'Thorn Volley',
    effectType: 'damage',
    range: 'ranged',
    cost: 1,
    archetypeHint: 'ranger',
    tags: ['nature', 'area'],
    buckets: ['beast', 'elemental'],
    constraints: { requiresArchetype: ['ranger'], minLevel: 1 },
    source: 'seed',
    version: 1
  },
  {
    key: 'pass-without-trace',
    name: 'Pass Without Trace',
    effectType: 'buff',
    range: 'self',
    cost: 1,
    archetypeHint: 'ranger',
    tags: ['stealth', 'mobility'],
    buckets: ['beast'],
    constraints: { requiresArchetype: ['ranger'], minLevel: 1 },
    source: 'seed',
    version: 1
  },
  {
    key: 'volley',
    name: 'Volley',
    effectType: 'damage',
    range: 'ranged',
    cost: 1,
    archetypeHint: 'ranger',
    tags: ['area', 'precision'],
    buckets: ['humanoid', 'goblinoid'],
    constraints: { requiresArchetype: ['ranger'], minLevel: 1 },
    source: 'seed',
    version: 1
  },
  // --- Higher-level catalog (progression / perks) ---
  {
    key: 'scorching-ray',
    name: 'Scorching Ray',
    effectType: 'damage',
    range: 'ranged',
    cost: 2,
    archetypeHint: 'mage',
    tags: ['fire', 'single-target'],
    buckets: ['elemental'],
    constraints: { requiresArchetype: ['mage'], minLevel: 2 },
    source: 'seed',
    version: 1
  },
  {
    key: 'arcane-ward',
    name: 'Arcane Ward',
    effectType: 'buff',
    range: 'self',
    cost: 2,
    archetypeHint: 'mage',
    tags: ['arcane', 'defense'],
    buckets: ['humanoid'],
    constraints: { requiresArchetype: ['mage'], minLevel: 2 },
    source: 'seed',
    version: 1
  },
  {
    key: 'smoke-bomb',
    name: 'Smoke Bomb',
    effectType: 'utility',
    range: 'self',
    cost: 1,
    archetypeHint: 'rogue',
    tags: ['concealment', 'area'],
    buckets: ['humanoid'],
    constraints: { requiresArchetype: ['rogue'], minLevel: 2 },
    source: 'seed',
    version: 1
  },
  {
    key: 'crippling-cut',
    name: 'Crippling Cut',
    effectType: 'debuff',
    range: 'melee',
    cost: 2,
    archetypeHint: 'rogue',
    tags: ['slow', 'precision'],
    buckets: ['humanoid'],
    constraints: { requiresArchetype: ['rogue'], minLevel: 2 },
    source: 'seed',
    version: 1
  },
  {
    key: 'spirit-mend',
    name: 'Spirit Mend',
    effectType: 'healing',
    range: 'touch',
    cost: 2,
    archetypeHint: 'cleric',
    tags: ['holy', 'support'],
    buckets: ['humanoid'],
    constraints: { requiresArchetype: ['cleric'], minLevel: 2 },
    source: 'seed',
    version: 1
  },
  {
    key: 'corded-trap',
    name: 'Corded Trap',
    effectType: 'control',
    range: 'ranged',
    cost: 2,
    archetypeHint: 'ranger',
    tags: ['restraint', 'single-target'],
    buckets: ['beast', 'goblinoid'],
    constraints: { requiresArchetype: ['ranger'], minLevel: 2 },
    source: 'seed',
    version: 1
  },
  {
    key: 'predator-instinct',
    name: 'Predator Instinct',
    effectType: 'buff',
    range: 'self',
    cost: 2,
    archetypeHint: 'ranger',
    tags: ['tracking', 'precision'],
    buckets: ['beast', 'dragonkin'],
    constraints: { requiresArchetype: ['ranger'], minLevel: 2 },
    source: 'seed',
    version: 1
  },
  {
    key: 'whirlwind',
    name: 'Whirlwind',
    effectType: 'damage',
    range: 'melee',
    cost: 2,
    archetypeHint: 'fighter',
    tags: ['area', 'cleave'],
    buckets: ['humanoid', 'goblinoid'],
    constraints: { requiresArchetype: ['fighter'], minLevel: 3 },
    source: 'seed',
    version: 1
  }
]
